/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu_Admin_3.HeThong;

import Login_Register_2.FormLogin;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoàng Thanh An
 */
public class Caculator extends javax.swing.JFrame {

    private int mouseY;
    private int mouseX;
    double num1 = 0, num2 = 0;
    String operator = null;

    public Caculator() {
        initComponents();
        t1.setBorder(BorderFactory.createLineBorder(Color.black, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bAC = new Menu_Admin_3.HeThong.Button();
        t1 = new javax.swing.JTextField();
        button0 = new Menu_Admin_3.HeThong.Button();
        button2 = new Menu_Admin_3.HeThong.Button();
        button3 = new Menu_Admin_3.HeThong.Button();
        button4 = new Menu_Admin_3.HeThong.Button();
        button5 = new Menu_Admin_3.HeThong.Button();
        button6 = new Menu_Admin_3.HeThong.Button();
        b7 = new Menu_Admin_3.HeThong.Button();
        b8 = new Menu_Admin_3.HeThong.Button();
        b9 = new Menu_Admin_3.HeThong.Button();
        b6 = new Menu_Admin_3.HeThong.Button();
        b5 = new Menu_Admin_3.HeThong.Button();
        b4 = new Menu_Admin_3.HeThong.Button();
        b1 = new Menu_Admin_3.HeThong.Button();
        b2 = new Menu_Admin_3.HeThong.Button();
        b3 = new Menu_Admin_3.HeThong.Button();
        button7 = new Menu_Admin_3.HeThong.Button();
        b0 = new Menu_Admin_3.HeThong.Button();
        button20 = new Menu_Admin_3.HeThong.Button();
        jLabel1 = new javax.swing.JLabel();
        bAC1 = new Menu_Admin_3.HeThong.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caculator");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        bAC.setBackground(new java.awt.Color(204, 204, 204));
        bAC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bAC.setText("AC");
        bAC.setFocusable(false);
        bAC.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        bAC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bACActionPerformed(evt);
            }
        });

        t1.setBackground(new java.awt.Color(0, 0, 0));
        t1.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        t1.setToolTipText("");
        t1.setFocusable(false);

        button0.setBackground(new java.awt.Color(204, 204, 204));
        button0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button0.setText("+/-");
        button0.setFocusable(false);
        button0.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(255, 153, 0));
        button2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("/");
        button2.setFocusable(false);
        button2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(255, 153, 0));
        button3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("x");
        button3.setFocusable(false);
        button3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(255, 153, 0));
        button4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setText("-");
        button4.setFocusable(false);
        button4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        button4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(255, 153, 0));
        button5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setText("+");
        button5.setFocusable(false);
        button5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        button5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(255, 153, 0));
        button6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setText("=");
        button6.setFocusable(false);
        button6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        button6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(102, 102, 102));
        b7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.setFocusable(false);
        b7.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(102, 102, 102));
        b8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.setFocusable(false);
        b8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(102, 102, 102));
        b9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.setFocusable(false);
        b9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(102, 102, 102));
        b6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.setFocusable(false);
        b6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(102, 102, 102));
        b5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.setFocusable(false);
        b5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(102, 102, 102));
        b4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.setFocusable(false);
        b4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(102, 102, 102));
        b1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.setFocusable(false);
        b1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(102, 102, 102));
        b2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.setFocusable(false);
        b2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(102, 102, 102));
        b3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.setFocusable(false);
        b3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(102, 102, 102));
        button7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setText(".");
        button7.setFocusable(false);
        button7.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        button7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(102, 102, 102));
        b0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.setFocusable(false);
        b0.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        b0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        button20.setBackground(new java.awt.Color(0, 0, 0));
        button20.setForeground(new java.awt.Color(255, 255, 255));
        button20.setText("X");
        button20.setFocusable(false);
        button20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caculator");

        bAC1.setBackground(new java.awt.Color(204, 204, 204));
        bAC1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bAC1.setText("DEL");
        bAC1.setFocusable(false);
        bAC1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        bAC1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bAC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAC1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAC1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = getLocation().x;
        int y = getLocation().y;
        int deltaX = evt.getX() - mouseX;
        int deltaY = evt.getY() - mouseY;
        setLocation(x + deltaX, y + deltaY);
    }//GEN-LAST:event_formMouseDragged

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button20ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "1");
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "2");
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "3");
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "4");
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "5");
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "6");
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "7");
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "8");
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "9");
    }//GEN-LAST:event_b9ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        if (!t1.getText().contains(".")) {
            t1.setText(t1.getText() + button7.getText());
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        t1.setText(t1.getText() + "0");
    }//GEN-LAST:event_b0ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        try {
            num1 = Double.parseDouble(t1.getText());
            t1.setText("");
            operator = "/";
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Syntax error.Please enter a number!");
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        try {
            num1 = Double.parseDouble(t1.getText());
            t1.setText("");
            operator = "*";
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Syntax error.Please enter a number!");
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        try {
            num1 = Double.parseDouble(t1.getText());
            t1.setText("");
            operator = "-";
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Syntax error.Please enter a number!");
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        try {
            num1 = Double.parseDouble(t1.getText());
            t1.setText("");
            operator = "+";
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Syntax error.Please enter a number!");
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed

        try {
            String input = t1.getText();
            if (input.isEmpty()) {
                return;
            }
            if (operator == null) {
                num1 = Double.parseDouble(input);
                t1.setText(input);
                return;
            }
            num2 = Double.parseDouble(input);
            double ans = 0;
            switch (operator) {
                case "+":
                    ans = num1 + num2;
                    break;
                case "-":
                    ans = num1 - num2;
                    break;
                case "*":
                    ans = num1 * num2;
                    break;
                case "/":
                    if (num2 == 0) {
                        JOptionPane.showMessageDialog(null, "Division by zero error!");
                        return;
                    }
                    ans = num1 / num2;
                    break;
            }
            if (ans % 1.0 == 0) {
                int intAns = (int) ans;
                t1.setText("" + intAns);
            } else {
                t1.setText("" + ans);
            }

            operator = null;
            num1 = ans;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Syntax error. Please enter a number!");
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void bACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bACActionPerformed
        // TODO add your handling code here:
        t1.setText("");
    }//GEN-LAST:event_bACActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        String inputText = t1.getText();
        try {
            double num1 = Double.parseDouble(inputText);
            num1 = num1 * (-1);
            if (num1 % 1.0 == 0) {
                int intAns = (int) num1;
                t1.setText("" + intAns);
            } else {
                t1.setText("" + num1);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Syntax error.Please enter a number!");
        }
    }//GEN-LAST:event_button0ActionPerformed

    private void bAC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAC1ActionPerformed
        String currentText = t1.getText();
        if (currentText.isEmpty() || currentText.length() == 1) {
            t1.setText("");
        } else {
            t1.setText(currentText.substring(0, currentText.length() - 1));
        }
    }//GEN-LAST:event_bAC1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i += 0.1) {
            String s = i + "";
            float f = Float.parseFloat(s);
            this.setOpacity(f);
            try {
                Thread.sleep(30);
            } catch (InterruptedException ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Menu_Admin_3.HeThong.Button b0;
    private Menu_Admin_3.HeThong.Button b1;
    private Menu_Admin_3.HeThong.Button b2;
    private Menu_Admin_3.HeThong.Button b3;
    private Menu_Admin_3.HeThong.Button b4;
    private Menu_Admin_3.HeThong.Button b5;
    private Menu_Admin_3.HeThong.Button b6;
    private Menu_Admin_3.HeThong.Button b7;
    private Menu_Admin_3.HeThong.Button b8;
    private Menu_Admin_3.HeThong.Button b9;
    private Menu_Admin_3.HeThong.Button bAC;
    private Menu_Admin_3.HeThong.Button bAC1;
    private Menu_Admin_3.HeThong.Button button0;
    private Menu_Admin_3.HeThong.Button button2;
    private Menu_Admin_3.HeThong.Button button20;
    private Menu_Admin_3.HeThong.Button button3;
    private Menu_Admin_3.HeThong.Button button4;
    private Menu_Admin_3.HeThong.Button button5;
    private Menu_Admin_3.HeThong.Button button6;
    private Menu_Admin_3.HeThong.Button button7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
